// nuxt-layers/ui-kit/app/components/List/ListAndroid/ListAndroidItem.vue
<script setup lang="ts">
import { provideListItemOptions } from './_provider.js';

export type ListAndroidItemVariant = 'regular' | 'accent' | 'destructive' | 'placeholder';

const props = withDefaults(defineProps<{
  /**
   * True if the element is clickable. This will add some additional visual changes to the element.
   */
  clickable?: boolean;
  /**
   * True if the item has a large size.
   */
  large?: boolean;
  /**
   * Visual variant.
   * @default 'regular'
   */
  variant?: ListAndroidItemVariant;
}>(), {
  variant: 'regular',
});
defineSlots<{
  left(): unknown;
  body(): unknown;
  bodyLeft(): unknown;
  bodyLeftInput(): unknown;
  bodyLeftLabel(): unknown;
  bodyLeftSubtitle(): unknown;
  bodyRight(): unknown;
}>();

const { b } = bem('tgui-list-android-item');

provideListItemOptions({
  large: computed(() => props.large ?? false),
});

const bodyLeftSlots = [
  { id: 'bodyLeftInput', name: 'input' },
  { id: 'bodyLeftLabel', name: 'label' },
  { id: 'bodyLeftSubtitle', name: 'subtitle' },
] as const;

const rootRef = useTemplateRef('root');
useRipples({
  enabled: () => props.clickable,
  containerRef: rootRef,
  clickRef: rootRef,
});
</script>

<template>
  <li ref="root" :class="b(variant, {clickable, 'no-left': !$slots.left})">
    <slot name="left"/>
    <slot name="body">
      <ListAndroidItemBody>
        <template #left>
          <slot name="bodyLeft">
            <ListAndroidItemBodyLeft v-if="bodyLeftSlots.some(s => s.id in $slots)">
              <template
                v-for="{id, name} in bodyLeftSlots.filter(s => s.id in $slots)"
                :key="id"
                #[name]
              >
                <slot :name="id" />
              </template>
            </ListAndroidItemBodyLeft>
          </slot>
        </template>
        <template v-if="'bodyRight' in $slots" #right>
          <slot name="bodyRight"/>
        </template>
      </ListAndroidItemBody>
    </slot>
  </li>
</template>

<style lang="scss">
@use "~scss/mixins";

.tgui-list-android-item {
  box-sizing: border-box;
  display: grid;
  grid-template-columns: auto 1fr;
  padding: 0 0 0 20px;
  background: transparent;
  overflow: hidden;
  position: relative;
  transition: 300ms ease-out;

  &--no-left {
    grid-template-columns: 1fr;
  }

  &--clickable {
    @include mixins.clickable;
  }

  @each $variant in ("regular", "destructive", "accent", "placeholder") {
    &--#{$variant} {
      color: var(--tgui-list-android-item-#{$variant}-color);
    }
  }
}
</style>

// packages/ui/src/components/List/ListAndroid/ListAndroidItem/ListAndroidItem.tsx
import { Dynamic } from 'solid-js/web';

import { Tappable, TappableProps } from '@/components/Tappable/Tappable.js';
import { cnCreate } from '@/css/cnCreate.js';
import { pickProps } from '@/helpers/pickProps.js';
import { pickChildren } from '@/helpers/pickChildren.js';
import { omitClasses } from '@/helpers/omitClasses.js';
import { omitProps } from '@/helpers/omitProps.js';
import { accessor } from '@/helpers/accessor.js';
import type { WithOptionalClasses } from '@/css/types.js';
import type { JSXIntrinsicElementAttrs } from '@/types/jsx.js';

import { e } from '../bem.js';
import { filterSlots } from '../slots.js';
import { ListAndroidItemBody } from '../ListAndroidItemBody/ListAndroidItemBody.js';
import { ListAndroidItemLeft } from '../ListAndroidItemLeft/ListAndroidItemLeft.js';

export type ListAndroidItemElementKey = 'root' | 'body' | 'inner';
export type ListAndroidItemVariant = 'regular' | 'accent' | 'destructive' | 'placeholder';
export type ListAndroidItemProps =
  & JSXIntrinsicElementAttrs<'li'>
  & {
  /**
   * True if the element is clickable. This will add some additional visual changes to the element.
   */
  clickable?: boolean;
  /**
   * True if the item has a large size.
   */
  large?: boolean;
  /**
   * Visual variant.
   */
  variant?: ListAndroidItemVariant;
}
  & WithOptionalClasses<ListAndroidItemElementKey, ListAndroidItemProps & {
  /**
   * True if this item is the first one in the list.
   */
  first: boolean;
}>;

import './ListAndroidItem.scss';

function Clickable(props: Omit<TappableProps<'button'>, 'component'>) {
  return <Tappable component="button" {...props}/>;
}

export function ListAndroidItem(props: ListAndroidItemProps & { first: boolean }) {
  const $cn = cnCreate(props, {
    root: v => [v.class, e('item', pickProps(v, ['large']), props.variant || 'regular')],
    inner: e('item-inner'),
  });
  const $clickable = accessor(props, 'clickable');

  return (
    <li
      {...omitProps(omitClasses(props), ['large', 'first', 'clickable'])}
      class={$cn().root}
    >
      <Dynamic component={$clickable() ? Clickable : 'div'} class={$cn().inner}>
        <ListAndroidItemLeft {...pickChildren(props)} {...filterSlots(props, 'left')}/>
        <ListAndroidItemBody
          {...pickChildren(props, ['first', 'large'])}
          {...filterSlots(props, 'body')}
        />
      </Dynamic>
    </li>
  );
}
