// apps/admin-panel/src/vue-ui/components/List/ListAndroid/ListAndroidItemBodyRightSwitch.vue
<script setup lang="ts">
import SwitchAndroid, {
  type SwitchAndroidEmits,
  type SwitchAndroidProps,
} from '@/vue-ui/components/Switch/SwitchAndroid.vue';

defineProps<SwitchAndroidProps>();
defineEmits<SwitchAndroidEmits>();
</script>

<template>
  <SwitchAndroid
    v-bind="$props"
    class="tgui-list-android-item-body-right-switch"
  />
</template>

<style lang="scss">
.tgui-list-android-item-body-right-switch {
  @each $part in ("bg", "checked-bg", "thumb-border-bg", "thumb-bg", "border-checked-bg") {
    --tgui-switch-android-#{$part}: var(--tgui-list-android-item-body-right-switch-#{$part});
  }
}
</style>

// packages/ui/src/components/List/ListAndroid/ListAndroidItemBodyRightSwitch/ListAndroidItemBodyRightSwitch.tsx
import {
  SwitchAndroid,
  type SwitchAndroidElementKey,
  type SwitchAndroidProps,
} from '@/components/Switch/SwitchAndroid/SwitchAndroid.js';
import { styled } from '@/css/styled.js';

import { e } from '../bem.js';

import './ListAndroidItemBodyRightSwitch.scss';

export type ListAndroidItemBodyRightSwitchElementKey = SwitchAndroidElementKey;
export type ListAndroidItemBodyRightSwitchProps = SwitchAndroidProps;

const StyledSwitch = styled(SwitchAndroid, { root: e('item-body-right-switch') });

export function ListAndroidItemBodyRightSwitch(props: SwitchAndroidProps) {
  return <StyledSwitch {...props}/>;
}
