// packages/ui/src/components/List/ListIos/ListIosItemBodyRightRadio/ListIosItemBodyRightRadio.tsx
import {
  RadioIos,
  type RadioIosElementKey,
  type RadioIosProps,
} from '@/components/Radio/RadioIos/RadioIos.js';
import { styled } from '@/css/styled.js';

import { e } from '../bem.js';

export type ListIosItemBodyRightRadioElementKey = RadioIosElementKey;
export type ListIosItemBodyRightRadioProps = RadioIosProps;

import './ListIosItemBodyRightRadio.scss';

const StyledRadio = styled(RadioIos, { root: e('item-body-right-radio') });

export function ListIosItemBodyRightRadio(props: RadioIosProps) {
  return <StyledRadio {...props}/>;
}

// _old/apps/admin-panel/src/vue-ui/components/List/ListIos/ListIosItemBodyRightRadio.vue
<script setup lang="ts">
import RadioIos, {
  type RadioIosEmits,
  type RadioIosProps,
} from '@/vue-ui/components/Radio/RadioIos.vue';

defineProps<RadioIosProps>();
defineEmits<RadioIosEmits>();
</script>

<template>
  <RadioIos
    v-bind="$props"
    class="root"
  />
</template>

<style scoped lang="scss">
.root {
  @each $part in ("border-color", "checked-color", "icon-color") {
    --tgui-radio-ios-#{$part}: var(--tgui-list-ios-item-body-right-radio-#{$part});
  }
}
</style>
