// packages/ui/src/components/List/ListIos/ListIosItemBodyRightSwitch/ListIosItemBodyRightSwitch.tsx
import {
  SwitchIos,
  type SwitchIosElementKey,
  type SwitchIosProps,
} from '@/components/Switch/SwitchIos/SwitchIos.js';
import { styled } from '@/css/styled.js';

import { e } from '../bem.js';

export type ListIosItemBodyRightSwitchElementKey = SwitchIosElementKey;
export type ListIosItemBodyRightSwitchProps = SwitchIosProps;

import './ListIosItemBodyRightSwitch.scss';

const StyledSwitch = styled(SwitchIos, { root: e('item-body-right-switch') });

export function ListIosItemBodyRightSwitch(props: SwitchIosProps) {
  return <StyledSwitch {...props}/>;
}

// _old/apps/admin-panel/src/vue-ui/components/List/ListIos/ListIosItemBodyRightSwitch.vue
<script setup lang="ts">
import SwitchIos, {
  type SwitchIosEmits,
  type SwitchIosProps,
} from '@/vue-ui/components/Switch/SwitchIos.vue';

defineProps<SwitchIosProps>();
defineEmits<SwitchIosEmits>();
</script>

<template>
  <SwitchIos
    v-bind="$props"
    class="tgui-list-ios-item-body-right-switch"
  />
</template>

<style lang="scss">
.tgui-list-ios-item-body-right-switch {
  --tgui-switch-ios-checked-bg: var(--tgui-list-ios-item-body-right-switch-checked-bg);
}
</style>
