// packages/ui/src/components/List/ListIos/ListIosItemBodyLeft/ListIosItemBodyLeft.tsx
import { Show } from 'solid-js';

import { cnCreate } from '@/css/cnCreate.js';
import { pickProps } from '@/helpers/pickProps.js';
import { omitProps } from '@/helpers/omitProps.js';
import { omitClasses } from '@/helpers/omitClasses.js';
import type { WithOptionalClasses } from '@/css/types.js';
import type { JSXIntrinsicElementAttrs } from '@/types/jsx.js';

import { e } from '../bem.js';
import { filterSlots } from '../slots.js';
import { ListIosItemBodyLeftLabel } from '../ListIosItemBodyLeftLabel/ListIosItemBodyLeftLabel.js';
import {
  ListIosItemBodyLeftSubtitle,
} from '../ListIosItemBodyLeftSubtitle/ListIosItemBodyLeftSubtitle.js';

import './ListIosItemBodyLeft.scss';

export type ListIosItemBodyLeftElementKey = 'root';
export type ListIosItemBodyLeftProps =
  & JSXIntrinsicElementAttrs<'div'>
  & {
  /**
   * True if the elements direction must be reversed. Applicable only when using ListIosItem with
   * the "large" = true property.
   */
  reversed?: boolean;
}
  & WithOptionalClasses<ListIosItemBodyLeftElementKey, ListIosItemBodyLeftProps & {
  large?: boolean;
}>;

export function ListIosItemBodyLeft(props: ListIosItemBodyLeftProps & {
  large?: boolean;
  reversed?: boolean;
}) {
  const $cn = cnCreate(props, {
    root: v => [
      v.class,
      e('item-body-left', pickProps(v, ['reversed', 'large'])),
    ],
  });
  return (
    <div {...omitProps(omitClasses(props), ['large', 'reversed'])} class={$cn().root}>
      <ListIosItemBodyLeftLabel {...filterSlots(props, 'bodyLeftLabel')}/>
      <Show when={props.large}>
        <ListIosItemBodyLeftSubtitle {...filterSlots(props, 'bodyLeftSubtitle')}/>
      </Show>
    </div>
  );
}

// _old/apps/admin-panel/src/vue-ui/components/List/ListIos/ListIosItemBodyLeft.vue
<script setup lang="ts">
import { bem } from 'vue-ui';

import { injectListItemOptions } from './provider.js';

defineProps<{
  /**
   * True if the elements direction must be reversed. Applicable only when using list item with
   * the "large" = true property.
   */
  reversed?: boolean;
}>();
defineSlots<{
  label(): any;
  subtitle(): any;
}>();

const { large } = injectListItemOptions();
const [b] = bem('tgui-list-ios-item-body-left');
</script>

<template>
  <div :class="b({ reversed, large })">
    <slot name="label" />
    <slot
      v-if="large"
      name="subtitle"
    />
  </div>
</template>

<style lang="scss">
.tgui-list-ios-item-body-left {
  display: flex;
  flex: 1 0 0;
  align-items: center;
  overflow: hidden;
  box-sizing: border-box;
  padding: 11px 16px 11px 0;

  &--reversed {
    flex-flow: column-reverse;
  }

  &--large {
    align-items: flex-start;
    flex-direction: column;
    justify-content: center;
  }
}
</style>
