// _old/apps/admin-panel/src/vue-ui/components/List/ListAndroid/ListAndroidItemBodyRightRadio.vue
<script setup lang="ts">
import RadioAndroid, {
  type RadioAndroidEmits,
  type RadioAndroidProps,
} from '@/vue-ui/components/Radio/RadioAndroid.vue';

defineProps<RadioAndroidProps>();
defineEmits<RadioAndroidEmits>();
</script>

<template>
  <RadioAndroid
    v-bind="$props"
    class="root"
  />
</template>

<style scoped>
.root {
  --tgui-radio-android-color: var(--tgui-list-android-item-body-right-radio-color);
  --tgui-radio-android-checked-color: var(--tgui-list-android-item-body-right-radio-checked-color);
}
</style>

// packages/ui/src/components/List/ListAndroid/ListAndroidItemBodyRightRadio/ListAndroidItemBodyRightRadio.tsx
import {
  RadioAndroid,
  type RadioAndroidElementKey,
  type RadioAndroidProps,
} from '@/components/Radio/RadioAndroid/RadioAndroid.js';
import { styled } from '@/css/styled.js';

import { e } from '../bem.js';

export type ListAndroidItemBodyRightRadioElementKey = RadioAndroidElementKey;
export type ListAndroidItemBodyRightRadioProps = RadioAndroidProps;

import './ListAndroidItemBodyRightRadio.scss';

const StyledRadio = styled(RadioAndroid, { root: e('item-body-right-radio') });

export function ListAndroidItemBodyRightRadio(props: RadioAndroidProps) {
  return <StyledRadio {...props}/>;
}
