// apps/tg-launcher/src/components/ErrorStatusPage.vue
<script setup lang="ts">
import { onMainButtonClick, setMainButtonParams } from '@telegram-apps/sdk-vue';
import { ValiError } from 'valibot';
import { onWatcherCleanup, useAttrs, watchEffect } from 'vue';
import { useI18n } from 'vue-i18n';
import type { GraphQLError } from 'vue-swr-gql';

import ServerErrorStatusPage from '@/components/ServerErrorStatusPage.vue';
import StatusPage from '@/components/StatusPage.vue';

export type ErrorStatusPageError =
  | { type: 'unknown'; cause: unknown }
  | { type: 'server'; cause: Error | GraphQLError }
  | { type: 'init'; timeout: number }
  | { type: 'iframe'; timeout?: boolean }
  | { type: 'init-data-missing' }
  | { type: 'config-invalid'; cause: ValiError<any> };

const { onRetry } = useAttrs();
defineProps<{ error: ErrorStatusPageError }>();
const emit = defineEmits<{ retry: [] }>();

const { t } = useI18n({
  messages: {
    en: {
      apiTimeoutMessage: 'Couldn\'t get information about the app (timed out {time}ms)',
      appUnknownMessage: 'An unknown error occurred while loading the application',
      configInvalidTitle: 'Incorrect configuration',
      defaultMessage: 'Unknown error occurred{error}',
      defaultTitle: 'Something went wrong',
      initDataMissingMessage: 'It is the most likely that the application was launched improperly',
      initDataMissingTitle: 'Init data is missing',
      loadTimeoutMessage: 'The app took too long to load',
      tryAgain: 'Try again',
    },
    ru: {
      apiTimeoutMessage: 'Не удалось получить информацию о приложении (тайм-аут {time}мс)',
      appUnknownMessage: 'Произошла неизвестная ошибка при загрузке приложения',
      configInvalidTitle: 'Некорректная настройка',
      defaultMessage: 'Произошла неизвестная ошибка{error}',
      defaultTitle: 'Что-то пошло не так',
      initDataMissingMessage: 'Скорее всего приложение было запущено некорректно',
      initDataMissingTitle: 'Данные инициализации отсутствуют',
      loadTimeoutMessage: 'Загрузка приложения оказалась слишком долгой',
      tryAgain: 'Попробовать снова',
    },
  },
});
const defaultTitle = t('defaultTitle');

watchEffect(() => {
  if (!onRetry) {
    return setMainButtonParams({ isVisible: false });
  }
  setMainButtonParams({ isVisible: true, text: t('tryAgain') });
  onWatcherCleanup(onMainButtonClick(() => {
    emit('retry');
  }));
});
</script>

<template>
  <StatusPage
    v-if="error.type === 'config-invalid'"
    state="error"
    :title="t('configInvalidTitle')"
  >
    {{ error.cause.message }}
  </StatusPage>

  <StatusPage
    v-else-if="error.type === 'init-data-missing'"
    state="error"
    :title="t('initDataMissingTitle')"
  >
    {{ t('initDataMissingMessage') }}
  </StatusPage>

  <ServerErrorStatusPage
    v-else-if="error.type === 'server'"
    :error="error.cause"
  />

  <StatusPage
    v-else-if="error.type === 'init'"
    state="error"
    :title="defaultTitle"
  >
    {{ t('apiTimeoutMessage', { time: error.timeout }) }}
  </StatusPage>

  <StatusPage
    v-else-if="error.type === 'iframe'"
    state="error"
    :title="defaultTitle"
  >
    {{ t(error.timeout ? 'loadTimeoutMessage' : 'appUnknownMessage') }}
  </StatusPage>

  <StatusPage
    v-else-if="error.type === 'unknown'"
    state="error"
    :title="defaultTitle"
  >
    {{
      t('defaultMessage', {
        error: error.cause instanceof Error
          ? `: ${error.cause.message}`
          : ''
      })
    }}
  </StatusPage>
</template>

// apps/telegram-launcher/src/components/ErrorStatusPage/ErrorStatusPage.tsx
import { createEffect, createMemo, Match, onCleanup, Show, Switch } from 'solid-js';
import { type UseGqlError, GraphQLError } from 'solid-gql';
import { is, looseObject, string, ValiError } from 'valibot';
import { onMainButtonClick, setMainButtonParams } from '@telegram-apps/sdk-solid';

import { useTranslator } from '@/providers/MainProvider.js';
import { StatusPage, type StatusPageProps } from '@/components/StatusPage/StatusPage.js';
import { Typography } from '@/components/Typography/Typography.js';

export type ErrorStatusPageError =
  | UseGqlError
  | ['server', UseGqlError]
  | ['init', timeout: number]
  | ['iframe', timeout?: boolean]
  | ['init-data-missing']
  | ['config-invalid', error: ValiError<any>];

function EnhancedStatusPage(props: Pick<StatusPageProps, 'title' | 'text'>) {
  return <StatusPage state="error" {...props} />;
}

/**
 * Component used to handle all kinds of errors.
 */
export function ErrorStatusPage(props: {
  error: ErrorStatusPageError;
  onRetry?: () => void;
}) {
  function withError<T>(fn: (
    err:
      | ['server', UseGqlError]
      | ['init', timeout: number]
      | ['iframe', timeout?: boolean]
      | ['init-data-missing']
      | ['unknown', error: Error]
      | ['config-invalid', error: ValiError<any>],
  ) => T): T {
    const { error } = props;
    return fn(Array.isArray(error)
      ? error
      : GraphQLError.is(error)
        ? ['server', error]
        : ['unknown', error]);
  }

  const t = useTranslator({
    en: {
      apiMessage: 'Server returned error: {{error}}',
      apiTimeoutMessage: 'Couldn\'t get information about the app (timed out {{time}}ms)',
      appUnknownMessage: 'An unknown error occurred while loading the application',
      configInvalidTitle: 'Incorrect configuration',
      defaultMessage: 'Unknown error occurred{{ error }}',
      defaultTitle: 'Something went wrong',
      initDataMissingMessage: 'It is the most likely that the application was launched improperly',
      initDataMissingTitle: 'Init data is missing',
      loadTimeoutMessage: 'The app took too long to load',
      requestMessage: 'Sneding request error: {{error}}',
      tryAgain: 'Try again',
    },
    ru: {
      apiMessage: 'Сервер вернул ошибку: {{error}}',
      apiTimeoutMessage: 'Не удалось получить информацию о приложении (тайм-аут {{time}}мс)',
      appUnknownMessage: 'Произошла неизвестная ошибка при загрузке приложения',
      configInvalidTitle: 'Некорректная настройка',
      defaultMessage: 'Произошла неизвестная ошибка{{ error }}',
      defaultTitle: 'Что-то пошло не так',
      initDataMissingMessage: 'Скорее всего приложение было запущено некорректно',
      initDataMissingTitle: 'Данные инициализации отсутствуют',
      loadTimeoutMessage: 'Загрузка приложения оказалась слишком долгой',
      requestMessage: 'Ошибка отправки запроса: {{error}}',
      tryAgain: 'Попробовать снова',
    },
  });
  const defaultTitle = t('defaultTitle');

  createEffect(() => {
    const { onRetry } = props;
    if (onRetry) {
      setMainButtonParams({ isVisible: true, text: t('tryAgain') });
      const offClick = onMainButtonClick(onRetry);
      onCleanup(() => {
        setMainButtonParams({ isVisible: false });
        offClick();
      });
    }
  });

  return (
    <Switch>
      {/* Invalid config */}
      <Match when={withError(e => e[0] === 'config-invalid' ? e[1] : false)}>
        {$err => (
          <EnhancedStatusPage title={t('configInvalidTitle')} text={$err().message}/>
        )}
      </Match>

      {/* Init data missing */}
      <Match when={withError(e => e[0] === 'init-data-missing')}>
        <EnhancedStatusPage title={t('initDataMissingTitle')} text={t('initDataMissingMessage')}/>
      </Match>

      {/* Server error */}
      <Match when={withError(e => e[0] === 'server' ? e[1] : false)}>
        {$error => (
          <Show
            when={(() => {
              const e = $error();
              return GraphQLError.is(e) ? e : false;
            })()}
            fallback={
              <EnhancedStatusPage
                title={defaultTitle}
                text={t('requestMessage', { error: $error().message })}
              />
            }
          >
            {$$error => {
              const $code = createMemo(() => {
                const { extensions } = $$error();
                return is(looseObject({ errorData: looseObject({ code: string() }) }), extensions)
                  ? extensions.errorData.code
                  : false;
              });

              return (
                <EnhancedStatusPage
                  title={defaultTitle}
                  text={
                    <>
                      {t('apiMessage', { error: $$error().message })}
                      <Show when={$code()}>
                        &nbsp;
                        <Typography component="span" weight="semibold">
                          ({$code()})
                        </Typography>
                      </Show>
                    </>
                  }
                />
              );
            }}
          </Show>
        )}
      </Match>

      {/* Init error */}
      <Match when={withError(e => e[0] === 'init' ? e[1] : false)}>
        {$timeout => (
          <EnhancedStatusPage
            title={defaultTitle}
            text={t('apiTimeoutMessage', { time: $timeout() })}
          />
        )}
      </Match>

      {/* Application load error */}
      <Match when={withError(e => e[0] === 'iframe' ? [e[1]] : false)}>
        {$tuple => (
          <EnhancedStatusPage
            title={defaultTitle}
            text={t($tuple()[0] ? 'loadTimeoutMessage' : 'appUnknownMessage')}
          />
        )}
      </Match>

      {/* Unknown error */}
      <Match when={withError(e => e[0] === 'unknown' ? e[1] : false)}>
        {$error => (
          <EnhancedStatusPage
            title={defaultTitle}
            text={(() => {
              const error = $error();
              return t('defaultMessage', { error: error instanceof Error ? `: ${error.message}` : '' });
            })()}
          />
        )}
      </Match>
    </Switch>
  );
}
