// apps/tg-launcher/src/components/AppLoader.vue
<script setup lang="ts">
import { isTimeoutError } from 'better-promises';
import { looseObject, nullish, string } from 'valibot';
import { onUnmounted, ref, shallowRef } from 'vue';
import { useI18n } from 'vue-i18n';
import { fetchApi, isApiError, useSWR } from 'vue-swr-shared';

import AppFrameBootstrapper from '@/components/AppFrameBootstrapper.vue';
import type { ErrorStatusPageError } from '@/components/ErrorStatusPage.vue';
import StatusPage from '@/components/StatusPage.vue';
import { appendRawLaunchParams } from '@/helpers/appendRawLaunchParams.js';

interface ErrorEvent {
  error: ErrorStatusPageError;
  fallbackUrl?: string;
}

const {
  fallbackUrl,
  appId,
  securedRawLaunchParams,
  initTimeout,
  loadTimeout,
  apiBaseUrl,
} = defineProps<{
  appId: number;
  apiBaseUrl: string;
  fallbackUrl?: string | null;
  initTimeout: number;
  loadTimeout: number;
  rawLaunchParams: string;
  securedRawLaunchParams: string;
}>();
const emit = defineEmits<{
  appDataRetrieved: [];
  error: [ErrorEvent];
  ready: [{ fallbackUrl?: string }];
}>();

const { t } = useI18n({
  messages: {
    en: {
      notFoundTitle: 'App not found',
      notFoundText: 'This application was not found',
      noAccessTitle: 'Nothing here',
      noAccessText: 'The application is inaccessible on your device',
    },
    ru: {
      notFoundTitle: 'Приложение не найдено',
      notFoundText: 'Это приложение не было найдено',
      noAccessTitle: 'Тут пусто',
      noAccessText: 'Приложение недоступно на Вашем устройстве',
    },
  },
});
const error = ref<ErrorStatusPageError>();
const appData = shallowRef<{ found: boolean; url?: string | null }>();

const controller = new AbortController();
const { signal } = controller;
const timeoutId = setTimeout(() => {
  controller.abort();
}, loadTimeout);
onUnmounted(() => {
  clearTimeout(timeoutId);
});

useSWR<{ url?: string | null }, {
  appId: number;
  apiBaseUrl: string;
  launchParams: string;
  signal?: AbortSignal;
}, Error>(
  ({ appId, apiBaseUrl, launchParams }) => `app-url-${appId}-${apiBaseUrl}-${launchParams}`,
  async ({ apiBaseUrl, appId, launchParams, signal }) => {
    const url = new URL(`apps/${appId}/telegram-url`, apiBaseUrl);
    url.searchParams.set('lp', launchParams);
    return fetchApi(url, looseObject({ url: nullish(string()) }), { signal });
  },
  {
    args: { appId, apiBaseUrl, launchParams: securedRawLaunchParams, signal },
    freshAge: 0,
    onSuccess({ data }) {
      appData.value = { found: true, url: data.url };
      emit('appDataRetrieved');
    },
    onError({ error: err }) {
      if (isApiError(err)) {
        if (err.data.code === 'ERR_APP_NOT_FOUND') {
          appData.value = { found: false };
        } else {
          error.value = { type: 'server', cause: err };
        }
        return;
      }
      error.value = isTimeoutError(error)
        ? { type: 'init', timeout: initTimeout }
        : { type: 'unknown', cause: error };
    },
    shouldRetry(error) {
      return !isTimeoutError(error) && (
        !isApiError(error)
        || error.data.code !== 'ERR_APP_NOT_FOUND'
      );
    },
    staleAge: 0,
  },
);
</script>

<template>
  <template v-if="error">
    <AppFrameBootstrapper
      v-if="fallbackUrl"
      :load-timeout="loadTimeout"
      :url="appendRawLaunchParams(fallbackUrl, rawLaunchParams)"
      @error="$emit('error', { error, fallbackUrl })"
      @ready="$emit('ready', { fallbackUrl })"
    />
    <div
      v-else
      v-show="false"
      @vue:mounted="$emit('error', { error })"
    />
  </template>
  <template v-else-if="appData">
    <AppFrameBootstrapper
      v-if="appData.url"
      :load-timeout="loadTimeout"
      :url="appendRawLaunchParams(appData.url, rawLaunchParams)"
      @error="error = { type: 'iframe', timeout: $event.timeout}"
      @ready="$emit('ready', {})"
    />
    <template v-else>
      <StatusPage
        :text="t(appData.found ? 'noAccessText' : 'notFoundText')"
        :title="t(appData.found ? 'noAccessTitle' : 'notFoundTitle')"
        @vue:mounted="$emit('ready', {})"
      />
    </template>
  </template>
</template>

// apps/telegram-launcher/src/components/AppLoader/AppLoader.tsx
import {
  createMemo,
  createSignal,
  Match,
  onMount,
  Show,
  Switch,
} from 'solid-js';
import { GraphQLError } from 'solid-gql';
import { accessor, pickProps } from 'solid-utils';
import { useGqlQuerySuspenseless } from 'shared';
import { isTimeoutError } from 'better-promises';

import type { ErrorStatusPageError } from '@/components/ErrorStatusPage/ErrorStatusPage.js';
import { AppContainer } from '@/components/AppContainer/AppContainer.js';
import { StatusPage } from '@/components/StatusPage/StatusPage.js';
import { createTimeoutSignal } from '@/async/createTimeoutSignal.js';
import { useTranslator } from '@/providers/MainProvider.js';

import { GetAppUrl } from './operations.js';

function BootstrappedContainer(props: {
  loadTimeout: number;
  onError: (error: ErrorStatusPageError) => void;
  onReady: () => void;
  url: string;
}) {
  return (
    <Show
      when={props.url.startsWith('http://')}
      fallback={
        <AppContainer
          {...pickProps(props, ['url', 'loadTimeout', 'onReady'])}
          onError={() => {
            props.onError(['iframe']);
          }}
          onTimeout={() => {
            props.onError(['iframe', true]);
          }}
        />
      }
    >
      {(() => {
        // Web doesn't support loading iframes with an HTTP URL in the secure context. All we
        // can do is just to redirect to the URL.
        window.location.href = props.url;
        props.onReady();
        return null;
      })()}
    </Show>
  );
}

export function AppLoader(props: {
  apiBaseURL: string;
  appID: number;
  fallbackURL?: Maybe<string>;
  initTimeout: number;
  loadTimeout: number;
  onAppDataRetrieved: () => void;
  onError: (error: ErrorStatusPageError, fallbackURL?: string) => void;
  onReady: (fallbackURL?: string) => void;
  rawLaunchParams: string;
  securedRawLaunchParams: string;
}) {
  const t = useTranslator({
    en: {
      notFoundTitle: 'App not found',
      notFoundText: 'This application was not found',
      noAccessTitle: 'Nothing here',
      noAccessText: 'The application is inaccessible on your device',
    },
    ru: {
      notFoundTitle: 'Приложение не найдено',
      notFoundText: 'Это приложение не было найдено',
      noAccessTitle: 'Тут пусто',
      noAccessText: 'Приложение недоступно на Вашем устройстве',
    },
  });
  const [$error, setError] = createSignal<ErrorStatusPageError>();
  const $timeout = accessor(props, 'initTimeout');
  const $timeoutSignal = createTimeoutSignal($timeout);
  const $appID = accessor(props, 'appID');

  const [$appData, setAppData] = createSignal<[appFound: boolean, url?: Maybe<string>]>();
  useGqlQuerySuspenseless(
    GetAppUrl,
    () => [[{
      appID: $appID(),
      launchParams: props.securedRawLaunchParams,
    }, { signal: $timeoutSignal() }]],
    {
      freshAge: 0,
      onSuccess({ data }) {
        setAppData([true, data.appTelegramURL]);
        props.onAppDataRetrieved();
      },
      onError({ error }) {
        if (GraphQLError.is(error) && error.isOfType('ERR_APP_NOT_FOUND')) {
          setAppData([false]);
        } else {
          setError(isTimeoutError(error) ? ['init', $timeout()] : error);
        }
      },
      shouldRetry(error) {
        return (
          !isTimeoutError(error)
          && !(GraphQLError.is(error) && error.isOfType('ERR_APP_NOT_FOUND'))
        );
      },
      staleAge: 0,
    },
  );

  return (
    <Switch>
      <Match when={$error()}>
        {$err => (
          <Show
            when={props.fallbackURL}
            fallback={(() => {
              // We don't have a fallback URL. It means that the application failed to load,
              // and we have nothing to display instead of the error screen.
              onMount(() => {
                props.onError($err());
              });
              return null;
            })()}
          >
            {$fallbackURL => (
              <BootstrappedContainer
                {...props}
                url={$fallbackURL()}
                onReady={() => {
                  props.onReady($fallbackURL());
                }}
                onError={error => {
                  props.onError(error, $fallbackURL());
                }}
              />
            )}
          </Show>
        )}
      </Match>
      <Match when={$appData()}>
        {$app => (
          <Switch>
            <Match when={$app()[1]}>
              {$telegramURL => {
                // As long as we passed secured launch parameters to the server, we will receive
                // them from it. Nevertheless, we should load the app using non-secured, initial
                // launch parameters. That's why we replace them here.
                const $url = createMemo(() => {
                  const url = new URL($telegramURL());
                  const hashParams = new URLSearchParams(url.hash.slice(1));
                  new URLSearchParams(props.rawLaunchParams).forEach((value, key) => {
                    hashParams.set(key, value);
                  });
                  url.hash = '#' + hashParams.toString();
                  return url.toString();
                });

                return (
                  <BootstrappedContainer
                    {...pickProps(props, ['loadTimeout', 'onReady'])}
                    url={$url()}
                    onError={setError}
                  />
                );
              }}
            </Match>
            <Match when={$app()[0] ? 'found' as const : 'not-found' as const}>
              {$status => {
                onMount(() => {
                  props.onReady();
                });
                const $isFound = () => $status() === 'found';
                return (
                  <StatusPage
                    title={t($isFound() ? 'noAccessTitle' : 'notFoundTitle')}
                    text={t($isFound() ? 'noAccessText' : 'notFoundText')}
                  />
                );
              }}
            </Match>
          </Switch>
        )}
      </Match>
    </Switch>
  );
}
