// packages/vue-kit/src/components/Radio/RadioAndroid.vue
<script setup lang="ts" generic="T extends string | number | boolean">
import { hapticFeedback } from '@tma.js/sdk-vue';
import { computed, useTemplateRef, watch } from 'vue';

import { bem } from '@/utils/bem';

const props = defineProps<{
  value: T;
  disabled?: boolean;
}>();

const currentValue = defineModel<T>({ required: true });
const checked = computed(() => currentValue.value === props.value);
const initiallyChecked = checked.value;
const { b, e } = bem('tgui-radio-android');

const rootRef = useTemplateRef('root');
const innerRef = useTemplateRef('inner');
let rootAnimation: Animation | undefined;
let innerAnimation: Animation | undefined;

watch(checked, () => {
  if (!rootAnimation || !innerAnimation) {
    const uncheckedColor = 'var(--unchecked-color)';
    const checkedColor = 'var(--checked-color)';
    const animationOptions = {
      duration: 200,
      direction: initiallyChecked ? 'reverse' : 'normal',
      easing: 'linear',
      fill: 'both',
    } as const;
    rootAnimation = rootRef.value!.animate({
      transform: ['scale(1)', 'scale(0.8)', 'scale(1)'],
      padding: ['0px', '0px', '2px'],
      borderColor: [uncheckedColor, uncheckedColor, checkedColor],
    }, animationOptions);
    innerAnimation = innerRef.value!.animate({
      boxShadow: [
        `0 0 0 0 ${uncheckedColor} inset`,
        `0 0 0 8px ${uncheckedColor} inset`,
        `0 0 0 6px ${checkedColor} inset`,
      ],
      borderColor: [uncheckedColor, uncheckedColor, checkedColor],
    }, animationOptions);
  } else {
    rootAnimation.reverse();
    innerAnimation.reverse();
  }
});
</script>

<template>
  <label ref="root" :class="b({ checked })">
    <input
      v-show="false"
      v-model="currentValue"
      :value
      :disabled
      type="radio"
      @change="hapticFeedback.selectionChanged.ifAvailable()"
    >
    <span ref="inner" :class="e('inner', { checked })"/>
  </label>
</template>

<style lang="scss">
@use "@/scss/mixins";

.tgui-radio-android {
  --unchecked-color: var(--tgui-radio-android-color, #C8C7CC);
  --checked-color: var(--tgui-radio-android-checked-color, #007AFF);
  @include mixins.clickable;
  display: inline-block;
  width: 20px;
  height: 20px;
  border-radius: 50%;
  border: 2px solid var(--unchecked-color);
  position: relative;
  box-sizing: border-box;

  &--checked {
    padding: 2px;
    border-color: var(--checked-color);
  }

  &__inner {
    display: block;
    border-radius: 50%;
    height: 100%;

    &--checked {
      box-shadow: 0 0 0 6px var(--checked-color) inset;
    }
  }
}
</style>

// packages/ui/src/components/Radio/RadioAndroid/RadioAndroid.tsx
import { createEffect, type JSX, mergeProps, on } from 'solid-js';

import { omitProps } from '@/helpers/omitProps.js';

import { bem } from '@/css/bem.js';
import { accessor } from '@/helpers/accessor.js';
import { cnCreate } from '@/css/cnCreate.js';
import type { WithOptionalClasses } from '@/css/types.js';

import './RadioAndroid.scss';

export type RadioAndroidElementKey = 'root' | 'input' | 'inner';
export type RadioAndroidProps =
  & WithOptionalClasses<RadioAndroidElementKey, RadioAndroidProps & {
    initiallyChecked: boolean;
  }>
  & JSX.IntrinsicElements['input'];

const [b, e] = bem('tgui-radio-android');

export function RadioAndroid(props: RadioAndroidProps) {
  const $checked = accessor(props, 'checked');
  const $cn = cnCreate(
    mergeProps(props, { initiallyChecked: $checked() }),
    {
      root: v => [v.class, b(v.initiallyChecked && 'initially-checked')],
      input: e('input'),
      inner: v => e('inner', v.initiallyChecked && 'initially-checked'),
    },
  );
  const initiallyChecked = $checked();
  let rootRef: HTMLLabelElement | undefined;
  let innerRef: HTMLSpanElement | undefined;
  let rootAnimation: Animation | undefined;
  let innerAnimation: Animation | undefined;

  let isMounted = false;

  createEffect(on([$checked], () => {
    if (!isMounted) {
      isMounted = true;
      return;
    }
    if (!rootAnimation || !innerAnimation) {
      const uncheckedColor = 'var(--unchecked-color)';
      const checkedColor = 'var(--checked-color)'
      const animationOptions = {
        duration: 200,
        direction: initiallyChecked ? 'reverse' : 'normal',
        easing: 'linear',
        fill: 'both',
      } as const;
      rootAnimation = rootRef!.animate({
        transform: ['scale(1)', 'scale(0.8)', 'scale(1)'],
        padding: ['0px', '0px', '2px'],
        borderColor: [uncheckedColor, uncheckedColor, checkedColor],
      }, animationOptions);
      innerAnimation = innerRef!.animate({
        boxShadow: [
          `0 0 0 0 ${uncheckedColor} inset`,
          `0 0 0 8px ${uncheckedColor} inset`,
          `0 0 0 6px ${checkedColor} inset`,
        ],
        borderColor: [uncheckedColor, uncheckedColor, checkedColor],
      }, animationOptions);
    } else {
      rootAnimation.reverse();
      innerAnimation.reverse();
    }
  }));

  return (
    <label ref={rootRef} class={$cn().root}>
      <input {...omitProps(props, ['classes'])} class={$cn().input} type="radio"/>
      <span ref={innerRef} class={$cn().inner}/>
    </label>
  );
}
